apiVersion: v1
kind: Pod
metadata:
  name: fsx-app
spec:
  initContainers:
  - name: set-lustre-cache
    image: amazonlinux:2
    command: ["/bin/sh","-c"]
    args: ["amazon-linux-extras install lustre -y && /sbin/lctl set_param llite.*.max_cached_mb=32"]
    securityContext:
      privileged: true
  containers:
  - name: app
    image: amazonlinux:2
    command: ["/bin/sh"]
    args: ["-c", "sleep 999999"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fsx-claim
